spring:
  liquibase:
    change-log:
    classpath: "/db/migrations/changeLog.xml"
  main:
    banner-mode: 'off'
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: library
  datasource:
    url: jdbc:mysql://localhost:1414/db
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        default_schema: db
  spring.liquibase:
    change-log: 'classpath:db/migration/changeLog.xml'
application:
  locale: ru
